### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Simpleguy12** [PatrickRorth/Twitch.TV#4]
Hey,
I used Simple Twitch: https://github.com/andriy921/Simple-Twitch till a few days but it stopped working, maybe you have the same issue.
When I start watching a stream, the picture remains black.
Also I cant scroll and I can see the titles of the streams. 

TV: Lg 55Uc970v (2014 4k tv) Softwareversion: 5.00.25 WEBOS: 1.4.0.2309 Afro achley

Best regards

**Comment by PatrickRorth** [comment]
Hi @Simpleguy12 

Thanks for the Issue, and my apologies for the **VERY** late respond.

Right now, i know there's a problem with the streams. This should be fixed in the 0.6 update. Altho! I am not able to release a workable version of 0.6, since LG has made a change in the ToS ("_access to the USB App Test service for webOS TV is now strictly limited to the webOS TV partners with NDA ONLY._"), so i can't compile the project on LG's site.

I am working with @Edocsyl to get a developer account, so this can be done. If this is fixed, we might be able to actually release the app, on the LG Store, on your TV.

We are crossing our fingers for this, and are releasing a workable version ASAP

**Comment by Simpleguy12** [comment]
Hey thanks for the answer, disn't see it.

Someone fixed Simple Twitch and it worked for me again till now.

What did LG change? Is it only changed on the new versions? My TV is running on 1.5 and I can still run apps from an usb stick.

Thanks a lot 

Best regards

**Comment by PatrickRorth** [comment]
Hi @Simpleguy12 

LG changed some things in the ToS, but only at the dev. point of view. That means that you should have no problem using the apps, when new updates are released or updated. But us developers, have to find another way to make this app work, and another way to upload it to LG, cause of the changes in the LG ToS.

But great to hear the Simple Twitch is working again! 👍
