### ISSUE TITLE
Update dropbox link

### ISSUE THREAD

**Issue by wonca22** [PatrickRorth/Twitch.TV#7]
Pls update dropbox link v.0.4 to v.0.6

thx

**Comment by PatrickRorth** [comment]
Hi wonca22

As of right now, i can't update the link, from v.0.4 to v.0.6, due to a update in the LG ToS("_access to the USB App Test service for webOS TV is now strictly limited to the webOS TV partners with NDA ONLY._"), i am not allowed to compile the project on the LG site.

This means that, as of right now, i can't release a workable version of the v.0.6.

I am working with @Edocsyl to get a developer account, so this can be done. If this is fixed, we might be able to actually release the app, on the LG Store, on your TV.

We are crossing our fingers for this, and are releasing a workable version ASAP

**Comment by mauriciozaffari** [comment]
@PatrickRorth any news regarding this? Is there a way to install the app manually?

**Comment by Edocsyl** [comment]
@mauriciozaffari there is no way at the moment. @PatrickRorth i have a 1.0 beta version. withou chat funcionality and remote -.- but i could upload it. but i dont know how long it takes to approve it from lg. you could make a gitter chat for bether communication.

**Comment by PatrickRorth** [comment]
@mauriciozaffari Sounds great! Idk about the timing aswell, but think it's worth it tho. So give it a go 👍 
I have also created a gitter chat : https://gitter.im/PatrickRorth/Twitch.TV

**Comment by mauriciozaffari** [comment]
@PatrickRorth you meant @Edocsyl. 😄

**Comment by PatrickRorth** [comment]
@mauriciozaffari lol yes i did. i'm sorry 😄
